#!/bin/bash

ACTIVATE_SCRIPT=venv/bin/activate

if [ ${OS:0:7} == "Windows" ]; then
    ACTIVATE_SCRIPT=venv/Scripts/activate
fi

OLDDIR=`pwd -P`
GIT_ROOT=`git rev-parse --show-toplevel`
GIT_ROOT=$(cd "$GIT_ROOT" >/dev/null && pwd -P)

# Go to the git root folder
cd "$GIT_ROOT"

# Enter python virtual environment
source ${ACTIVATE_SCRIPT}

# Run syntax check
flake8 --exclude="migrations,data" nurseregister_site/ nurseregister/
STATUS=$?

# Exit python virtual environment
deactivate

# Get back to previous dir and exit
cd "$OLDDIR"
exit $STATUS

